[package]
name = "lunellum"
version = "0.1.0"
edition = "2024"
authors = ["tousef_refuge"]
description = "A version control system built specifically for writers"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.0", features = ["derive", "cargo"] }
chrono = "0.4.45"
colored = "3.1.1"
flate2 = "1.1.10"
ignore = "0.4.33"
serde = { version = "1.0.229", features = ["derive"] }
sha1 = "0.11.0"
postcard = { version = "1.1.3", features = ["alloc"] }
walkdir = "2.5.0"

[features]
debug = []
